services:
  app:
    ports:
      - "8081:8081"
    env_file:
      - example.env
    build:
      dockerfile: deployment/app/Dockerfile
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    logging:
      driver: "json-file"
      options:
        max-size: "2G"
        max-file: "1"

  postgres:
    image: postgres:15
    restart: always
    env_file:
      - example.env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "$$POSTGRES_USER", "-d", "$$POSTGRES_DB" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  migrations:
    build:
      dockerfile: deployment/migrations/Dockerfile
    env_file:
      - example.env
    depends_on:
      postgres:
        condition: service_healthy