###
POST http://localhost:8081/register

{
    "email":"qq@qq.qq",
    "password":"123"
}

####

###
POST http://localhost:8081/login
User-Agent: chrome

{
    "email":"qq@qq.qq",
    "password":"123"
}
####

###
POST http://localhost:8081/refreshTokens

{
    "fingerprint":"chrome",
    "refreshToken":""
}

####


GET http://localhost:8081/build
